### ISSUE TITLE
icon does not show when inactive and the content does not show either - Mac

### ISSUE THREAD

**Issue by ms-carterk** [ImStuartJones/undercast#1]
Mac OS 10.12.4 - MBP Retina 15inch, early 2013

**Comment by ImStuartJones** [comment]
I'm not sure what happened on the Overcast.fm servers to make Undercast fail to load it, but it looks like the latest version of Electron fixes it. I've updated the package.json requirements to reflect this and uploaded a new macOS build.

**Comment by ckegelman** [comment]
@ImStuartJones thank you, this did fix the issue for me.
