### ISSUE TITLE
Icon doesn't show when inactive on light menubar

### ISSUE THREAD

**Issue by twhite96** [ImStuartJones/undercast#2]
Icon doesn't show when inactive on light menubar but does on dark. Content loads, but not the icon.

**Comment by ImStuartJones** [comment]
Thanks for bringing this to my attention. Undercast's tray icons were hardcoded to white. I've added support for light and dark macOS menubar schemes as reported here:

https://github.com/electron/electron/blob/master/docs/api/native-image.md#template-image

The latest binary should fix this problem. It can be downloaded here: https://github.com/ImStuartJones/undercast/raw/master/releases/Undercast.app.zip

**Comment by twhite96** [comment]
Thanks @ImStuartJones.

**Comment by twhite96** [comment]
@ImStuartJones the menubar item is still white in the latest binary.

**Comment by ImStuartJones** [comment]
Whoops. These things tend to work better when you actually remember to push the code to Github. Please try again now.

**Comment by twhite96** [comment]
Hahaha. No worries. I'll download again now.
