### ISSUE TITLE
Pasting into input fields on login screen does not work

### ISSUE THREAD

**Issue by comatory** [ImStuartJones/undercast#3]
No idea why this doesn't work. I'm using password manager and I can't paste anything on login screen.

**Comment by ImStuartJones** [comment]
I can reproduce the issue on my end. It appears to be related to https://github.com/electron/electron/issues/2402 I'll look into seeing if I can't get this fixed.

**Comment by ImStuartJones** [comment]
That appears to be what it was. A new version has been uploaded that should allow pasting into the login window.
