### ISSUE TITLE
App white/blank when in path with irregular characters

### ISSUE THREAD

**Issue by wickles** [ImStuartJones/undercast#5]
Hi, on Windows 10 when I open the app from a path with non-standard characters, e.g. an octothorpe '#' in my case, the window opens but it is just blank. It works fine from regular paths with only alphanumeric characters. Not sure if this is an issue with your app/implementation or upstream in node.

**Comment by ImStuartJones** [comment]
Hmm. Electron is based on web technologies, so the '#' character is probably being read as a hash URL property somewhere in the code. I can't see any obvious places in Overcast where a '#' character in a file location would cause this behavior, so I'm going to assume it's an upstream issue. I'm going to close this issue and recommend you run the application from a folder without irregular characters. Sorry for the trouble!
